# Generated by Django 3.0 on 2022-04-15 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime_created', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('datatime_lifetime', models.DateTimeField(auto_now=True, verbose_name='время существования')),
                ('datatime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('todo', models.CharField(max_length=30, verbose_name='Задание')),
                ('leadtime', models.DateTimeField(verbose_name='время выполнения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ('todo',),
            },
        ),
    ]
