# Generated by Django 3.0 on 2022-04-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='todo',
            field=models.CharField(max_length=30),
        ),
    ]
