# Generated by Django 3.0 on 2022-04-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_dos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datatime_created',
            new_name='datetime_created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='datatime_deleted',
            new_name='datetime_deleted',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='datatime_lifetime',
            new_name='datetime_lifetime',
        ),
    ]
